title: Mikhail Savochkin | C C++ Go Developer | Cloud Computing | Game Development | Subutai
description: > # this means to ignore newlines until "baseurl:"
  I'm a software developer. So most of the posts will be about development. 
  Most probably you will see posts about Subutai - the project I'm working on,
  about how we make games in Idea-X and about our game Cold Space.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://crioto.com" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Mikhail Savochkin # add your name
author-img: mikhail-savochkin.png # add your photo
about-author: C/C++/Go Developer. Working in a cloud computing sphere. Game Development Hobbyist. Experienced UE4 Developer. # add description
twitter: crioto # add your Twitter handle
facebook: crioto # add your Facebook handle
github: crioto # add your Github handle
linkedin: crioto # add your Linkedin handle
email: crioto@users.noreply.github.com # add your Email address

# Disqus
discus-identifier: crioto-com # add your discus identifier

# Tracker
analytics: UA-20425139-1  # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
