# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Crioto's Weblog
email: root@localhost
description: > # this means to ignore newlines until "baseurl:"
    Using this blog as a personal storage of my ideas, thoughts, projects, experiments and life
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://crioto.github.io" # the base hostname & protocol for your site
twitter_username: crioto
github_username:  crioto

# Build settings
markdown: kramdown
