# Site settings
title: Mikhail Savochkin's blog
email: i@crioto.com
description: > # this means to ignore newlines until "baseurl:"
    I am posting posts about things
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://www.crioto.com" # the base hostname & protocol for your site
twitter_username: crioto
github_username:  crioto

# Build settings
markdown: kramdown
